name: flutter_super_html_viewer
description: A Flutter plugin that provides a HtmlViewer widget on multiple platforms
homepage: https://github.com/dab246/flutter_super_html_viewer.git
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  flutter_inappwebview: ^6.1.4

  url_launcher: ^6.3.0

  universal_html: ^2.2.4


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
